# Generated by Django 4.2.6 on 2023-10-19 19:22

from django.db import migrations, models
import django.db.models.deletion
from django.db import migrations
from django.contrib.contenttypes.models import ContentType
from django.contrib.auth.models import Permission

def create_review_submissions_permission(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')
    Permission = apps.get_model('auth', 'Permission')
    reviewers = Group.objects.get(name='Reviewers')
    Submission = apps.get_model('submissions', 'Submission')
    content_type = ContentType.objects.get_for_model(Submission)
    permission = Permission.objects.create(
        codename='can_review_submissions',
        name='Can review submissions',
        content_type=content_type,
    )
    reviewers.permissions.add(permission)

create_review_submissions_permission.required = True

def create_editor_permissions(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')
    Permission = apps.get_model('auth', 'Permission')
    editors = Group.objects.create(name='Editors')
    editors.permissions.add(Permission.objects.get(codename='can_review_submissions'))

create_editor_permissions.required = True

class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Submission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("author_name", models.CharField(max_length=255)),
                ("article_name", models.CharField(max_length=255)),
                ("date_submitted", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=10,
                    ),
                ),
                ("file_url", models.FileField(upload_to="submissions/")),
            ],
            options={
                "db_table": "submissions",
            },
        ),
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("reviewer_name", models.CharField(max_length=255)),
                ("date_reviewed", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=10,
                    ),
                ),
                ("comments", models.TextField()),
                (
                    "submission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="submissions.submission",
                    ),
                ),
            ],
            options={
                "db_table": "reviews",
            },
        ),
    ]
