# Generated by Django 4.2.6 on 2023-10-25 16:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("submissions", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="submission",
            name="file_url",
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
    ]
