# Generated by Django 4.2.6 on 2023-10-24 20:07

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("submissions", "0002_review_alter_submission_history_change_type"),
        ("submissions", "0002_submission_reviewer_1_submission_reviewer_2_and_more"),
    ]

    operations = []
