# Generated by Django 4.2.6 on 2023-11-01 15:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("submissions", "0002_submission_file_url"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="submission",
            name="reviewer_1",
        ),
        migrations.RemoveField(
            model_name="submission",
            name="reviewer_2",
        ),
        migrations.RemoveField(
            model_name="submission",
            name="reviewer_3",
        ),
        migrations.AlterField(
            model_name="review",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("approved", "Approved"),
                    ("rejected", "Rejected"),
                    ("Needs Revision", "Needs Revision"),
                ],
                default="pending",
                max_length=15,
            ),
        ),
    ]
