# Generated by Django 4.2.6 on 2023-11-03 17:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("submissions", "0003_remove_submission_reviewer_1_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="submission",
            name="reviewers",
            field=models.ManyToManyField(
                related_name="assigned_submissions", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
